version: '3'

services:
  oracle-db1:
    image: container-registry.oracle.com/database/free
    container_name: oracle-db1
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=1230
    networks:
      - oracle-network

  oracle-db2:
    image: container-registry.oracle.com/database/free
    container_name: oracle-db2
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PDB=ORCLPDB2
      - ORACLE_PWD=1230
    networks:
      - oracle-network

networks:
  oracle-network:
    driver: bridge
